spring:
  profiles:
    active: dev
  application:
    name: bankcards
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: ${SPRING_LIQUIBASE_CHANGELOG:classpath:db/migration/db.changelog-master.yaml}
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v3

springdoc:
  swagger-ui:
    urls:
      - name: Generated API
        url: /v3/api-docs
      - name: YAML Specification
        url: /openapi.yaml

security:
  jwt:
    secret: ${JWT_SECRET:uY8p0zS9m4Xk6+6JGZveHFkNjEcNWef39/C4R2tQeM0=}
    access-token-ttl: ${JWT_ACCESS_TTL:900}
    refresh-token-ttl: ${JWT_REFRESH_TTL:2592000}
    issuer: bankcards-api

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
