openapi: 3.0.3
info:
  title: Bank Cards Admin API
  version: 1.0.0
  description: >
    Admin endpoints for managing bank cards. Security is disabled in the current
    environment; once authentication is in place, update the `security` section accordingly.
servers:
  - url: http://localhost:8901/api/v3
    description: Local development
tags:
  - name: Admin
    description: Administrative operations over cards
paths:
  /admin/card/create:
    post:
      tags:
        - Admin
      operationId: createCard
      summary: Создать карту для клиента
      description: >
        Выпускает новую карту для переданного клиента. В ответ возвращается зашифрованная карта
        и вспомогательные данные. Сырый PAN возвращается только в ответе на этот запрос.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardCreateRequestDto'
      responses:
        '201':
          description: Карта успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardCreateResponseDto'
        '204':
          description: Клиент с указанным `ownerId` не найден
        '409':
          description: Карта с таким PAN уже существует (коллизия генератора)
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Внутренняя ошибка сервиса
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    CardCreateRequestDto:
      type: object
      required:
        - ownerId
      properties:
        ownerId:
          type: string
          format: uuid
          description: Идентификатор клиента, которому будет принадлежать карта
    CardCreateResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор созданной карты
        ownerId:
          type: string
          format: uuid
          description: Идентификатор владельца карты
        maskedPan:
          type: string
          description: Маскированный номер карты для отображения в интерфейсе
        expiryMonth:
          type: integer
          minimum: 1
          maximum: 12
          description: Месяц окончания срока действия
        expiryYear:
          type: integer
          description: Год окончания срока действия
        plainPan:
          type: string
          description: Сырый PAN, возвращается только при создании карты
